export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const SIDEBAR_OPEN = "SIDEBAR_OPEN";

export const CREATE_ENTRY_SUCCESS = "CREATE_ENTRY_SUCCESS";
export const CREATE_ENTRY_REQUEST = "CREATE_ENTRY_REQUEST";
export const CREATE_ENTRY_FAILURE = "CREATE_ENTRY_FAILURE";

export const UPDATE_ENTRY_SUCCESS = "UPDATE_ENTRY_SUCCESS";
export const UPDATE_ENTRY_REQUEST = "UPDATE_ENTRY_REQUEST";
export const UPDATE_ENTRY_FAILURE = "UPDATE_ENTRY_FAILURE";

export const LOAD_ENTRIES_SUCCESS = "RELOAD_ENTRIES_SUCCESS";
export const LOAD_ENTRIES_REQUEST = "RELOAD_ENTRIES_REQUEST";
export const LOAD_ENTRIES_FAILURE = "RELOAD_ENTRIES_FAILURE";

export const SYNC_ENTRIES_SUCCESS = "SYNC_ENTRIES_SUCCESS";
export const SYNC_ENTRIES_REQUEST = "SYNC_ENTRIES_REQUEST";
export const SYNC_ENTRIES_FAILURE = "SYNC_ENTRIES_FAILURE";